# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a38fce0262be48fef20dbe2a08ef0c8e8b42e8cf62d3ced96712a57b41f6addcc6d22914cf611e20b8a8f1b52288fdccfe79ac9abe73162aec397eb2b04eea

test:
  secret_key_base: 5fb67943202fcd32121f5db3d4ab0f278b25f6a6b1b51aea9d115e55e2da8195f986ebed45706e62abd770aeb4ba5ff4709f9b6915d3f5ca2d9560fa3f68e252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
